
version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  test:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/test-results/testDebugUnitTest
          destination: test-results
      - store_test_results:
          path: app/build/test-results/
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

  ktlint:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlint --no-daemon --max-workers 2

workflows:
  test:
    jobs:
      - test
      - ktlint