
version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/test-results/testDebugUnitTest
          destination: test-results
      - store_test_results:
          path: app/build/test-results/
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
